export const userConstants = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  ICCAPI_INITIALISED: 'USER_ICCAPI_INITIALISED',
  LOGOUT: 'USER_LOGOUT',
  BACKUP_KEY: 'BACKUP_KEY',
  CRYPTO_AVAILABLE: 'CRYPTO_AVAILABLE',
  USER_MODIFIED: 'USER_MODIFIED',
  HCP_MODIFIED: 'HCP_MODIFIED',
}
